version: "2"
services:
  topics-ui:
    image: "landoop/kafka-topics-ui"
    ports:
      - "8001:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://212.189.145.44:8082"
      PROXY: "true"

  schema-registry-ui:
    image: "landoop/schema-registry-ui"
    ports:
      - "8002:8000"
    environment:
      SCHEMAREGISTRY_URL: "http://212.189.145.44:8081"
      PROXY: "true"

  connect-ui:
    image: "landoop/kafka-connect-ui"
    ports:
      - "8003:8000"
    environment:
      CONNECT_URL: "http://212.189.145.44:8083"
